version: 0.0
os: linux

files:
  - source: /
    destination: /server
permissions:
  - object: /server/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 720
      runas: root