name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_NAME: web-cloning
  BK_NAME: samplebk1234
  APP_NAME: sampleApp
  DEPLOY_GROUP: sampleDeployGroup   

jobs:
  build:
    name: Build, EC2
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Transfer to EC2
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_MANAGE_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGE_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BK_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name $APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOY_GROUP --s3-location bucket=$BK_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
